stock-exchange-private/website/views.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from sqlalchemy import null
from flask_login import login_required, current_user
from website.models import User_Stock_Info
import yfinance as yf
import requests
from . import db
from datetime import datetime
from cachetools import cached, TTLCache
import re

cache = TTLCache(maxsize=256, ttl=3600)


views = Blueprint("views", __name__)


def subscribe_user(email, user_group_email, api_key):

    resp = requests.post(
        f"https://api.mailgun.net/v3/lists/{user_group_email}/members",
        auth=("api", api_key),
        data={"subscribed": True, "address": email},
    )

    print(resp.status_code)

    return resp


@views.route("/", methods=["GET", "POST"])
def home():

    # if user submits the form
    if request.method == "POST":

        email = request.form.get("email")

        subscribe_user(
            email=email,
            user_group_email="newsletter@sandbox19ce4f1055834080aa0b077e71af98f4.mailgun.org",
            api_key="6325dc122ba4abdff8c7bec3d00cc77e-0677517f-7ce70962",
        )

        flash("Tuned in!", category="success")

    return render_template(
        "home.html",
        user=current_user,
        #FB_open=round(FB["Open"][0], 2),
        #FB_high=round(FB["High"][0], 2),
        #FB_close=round(FB["Close"][0], 2),
        #Apple_open=round(Apple["Open"][0], 2),
       #  Apple_high=round(Apple["High"][0], 2),
        # Apple_close=round(Apple["Close"][0], 2),
        # Amazon_open=round(Amazon["Open"][0], 2),
         #Amazon_high=round(Amazon["High"][0], 2),
         # #Amazon_close=round(Amazon["Close"][0], 2),
         #Netflix_open=round(Netflix["Open"][0], 2),
         #Netflix_high=round(Netflix["High"][0], 2),
         #Netflix_close=round(Netflix["Close"][0], 2),
         #Google_open=round(Google["Open"][0], 2),
         #Google_high=round(Google["High"][0], 2),
         #Google_close=round(Google["Close"][0], 2),
         #Nvidia_open=round(Nvidia["Open"][0], 2),
         #Nvidia_high=round(Nvidia["High"][0], 2),
         #Nvidia_close=round(Nvidia["Close"][0], 2),
         #AMD_open=round(AMD["Open"][0], 2),
         #AMD_high=round(AMD["High"][0], 2),
         #AMD_close=round(AMD["Close"][0], 2),
         #Visa_open=round(Visa["Open"][0], 2),
         #Visa_high=round(Visa["High"][0], 2),
         #Visa_close=round(Visa["Close"][0], 2),
         #Mastercard_open=round(MasterCard["Open"][0], 2),
         #Mastercard_high=round(MasterCard["High"][0], 2),
         #Mastercard_close=round(MasterCard["Close"][0], 2),
        #Twitter_open=round(Twitter["Open"][0], 2),
        #Twitter_high=round(Twitter["High"][0], 2),
        #Twitter_close=round(Twitter["Close"][0], 2),
         #Tesla_open=round(Tesla["Open"][0], 2),
         #Tesla_high=round(Tesla["High"][0], 2),
         #Tesla_close=round(Tesla["Close"][0], 2),
         #JP_Morgan_open=round(JP_Morgan["Open"][0], 2),
         #JP_Morgan_high=round(JP_Morgan["High"][0], 2),
         #JP_Morgan_close=round(JP_Morgan["Close"][0], 2),
        # Walmart_open=round(Walmrt["Open"][0], 2),
         #Walmart_high=round(Walmrt["High"][0], 2),
         #Walmart_close=round(Walmrt["Close"][0], 2),
         #Coca_Cola_open=round(Coca_Cola["Open"][0], 2),
         #Coca_Cola_high=round(Coca_Cola["High"][0], 2),
         #Coca_Cola_close=round(Coca_Cola["Close"][0], 2),
    )


@views.route("/deposit")
@login_required
def deposit():
    return render_template("deposit.html", user=current_user)


@views.route("/deposit", methods=["GET", "POST"])
@login_required
def deposit2():
    deposit_amount = request.form["amount"]
    cvv = request.form["CVV"]

    if not isValidCVVNumber(cvv):
        flash("CVV is invalid", category="error")
        return render_template("deposit.html", user=current_user)

    if is_valid_float(deposit_amount) and isValidCVVNumber(cvv):
        if float(deposit_amount) > 0:
            current_user.balance += float(deposit_amount)
            db.session.commit()
            flash("Deposit successful!", category="success")
            return render_template("deposit.html", user=current_user)
        else:
            flash("Deposit amount must be greater than 0", category="error")
            return render_template("deposit.html", user=current_user)
    return render_template("deposit.html", user=current_user)


@views.route("/withdraw")
@login_required
def withdraw():
    return render_template("withdraw.html", user=current_user)


@views.route("/withdraw", methods=["GET", "POST"])
@login_required
def withdraw2():
    withdraw_amount = request.form["amount"]
    ban = request.form["BAN"]

    if int(ban) < 0:
        flash("Enter a valid bank account number", category="error")
        return render_template("withdraw.html", user=current_user)

    if is_valid_float(withdraw_amount) and int(ban) > 0:
        if (
            float(withdraw_amount) > 0
            and float(withdraw_amount) <= current_user.balance
        ):
            current_user.balance -= float(withdraw_amount)
            db.session.commit()
            flash("Withdrawal successful!", category="success")
            return render_template("withdraw.html", user=current_user)
        else:
            flash(
                "Withdrawal amount must be greater than 0 and less than your balance",
                category="error",
            )
            return render_template("withdraw.html", user=current_user)
    return render_template("withdraw.html", user=current_user)


@views.route("/termsofservice")
def termsofservice():
    return render_template("termsofservice.html", user=current_user)


@views.route("/privacy")
def privacy():
    return render_template("privacy.html", user=current_user)


recent_transactions = []


@views.route("/portfolio")
def portfolio():
    sum_ = 0
    all_stocks = []

    for i in User_Stock_Info.query.filter_by(user_id=current_user.id):
        sum_ += float(i.stock_price) * float(i.quantity)

        if i.quantity > 0:
            all_stocks.append(i)

    new_list = sorted(
        all_stocks, key=lambda x: float(x.stock_price) * float(x.quantity), reverse=True
    )

    actual_new_list = []
    for i in new_list:
        actual_new_list.append(
            [round(float(i.stock_price), 2), float(i.quantity), i.stock_id]
        )

    for i in actual_new_list:
        if float(i[1]) == float(0):
            actual_new_list.remove(i)

    our_users_list = []
    for i in recent_transactions:
        if i[0] == current_user.id:
            our_users_list.append(i)

    print(our_users_list)

    return render_template(
        "portfolio.html",
        user=current_user,
        account_balance=round(current_user.balance, 2),
        account_profit=round(current_user.profit, 2),
        account_holdings=round(sum_, 2),
        most_valuable=actual_new_list,
        recent=our_users_list,
    )


@views.route("/newsandinsights")
def newsandinsights():
    return render_template("newsandinsights.html", user=current_user)


@views.route("/lawsandpolicies")
def lawsandpolicies():
    return render_template("lawsandpolicies.html", user=current_user)


@views.route("/stockists")
def stockists():
    return render_template("stockists.html", user=current_user)


@views.route("/newsAndInsights")
def news():
    articles = Article.query.all()
    return render_template("newsAndInsights.html", events=articles)


@views.route("/event/<int:id>")
def event(id):
    event = Article.query.get_or_404(id)
    return render_template("event.html", event=event)


@views.route("/viewportfolio")
def view_portfolio():
    return render_template("viewportfolio.html", user=current_user)


@views.route("/buy")
@login_required
def buy():
    return render_template("buy.html", user=current_user)


@views.route("/buy", methods=["POST", "GET"])
@login_required
def buy2():
    # symbol
    text = request.form["text"].upper()
    print(bool(get_ticker(text) == None))

    if (yf.Ticker(text).info)["regularMarketPrice"] == None:
        flash("Please enter a valid stock symbol", category="error")
        return render_template("buy.html", user=current_user)

    # quantity
    text2 = request.form["text2"]

    if is_valid_float(text2) == False:
        flash("Please enter a valid quantity", category="error")
        return render_template("buy.html", user=current_user)
    # Want to see if row in database already exists with user_id and stock_id, returns true if it exists
    if bool(
        User_Stock_Info.query.filter_by(user_id=current_user.id, stock_id=text).first()
    ):
        print("yee")

        user_row = User_Stock_Info.query.filter_by(
            user_id=current_user.id, stock_id=text
        ).first()

        print(user_row)

        if current_user.balance >= get_current_price(text) * float(text2):
            old_quantity = user_row.quantity
            new_quantity = float(old_quantity) + float(text2)
            old_profit = current_user.profit
            new_profit = float(old_profit) - (
                float(get_current_price(text)) * float(text2)
            )
            print(new_profit)
            user_row.quantity = new_quantity
            current_user.profit = new_profit
            db.session.commit()
            current_user.balance -= get_current_price(text) * float(text2)
            db.session.commit()

            print("found existing row and updated quantity")
            flash("Stocks Bought successfully!", category="success")

            recent_transactions.append(
                [
                    current_user.id,
                    user_row.stock_id,
                    text2,
                    datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
                    "+",
                ]
            )

            return render_template("buy.html", user=current_user)
        else:
            print("found existing row but not enough money")

stock-exchange-private/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="icon" href="../static/bully.svg">
  <link rel='stylesheet' id='cludo-styles-css'
    href='https://www.cludo.com/wp-content/themes/cludo/build/css/theme.min.css?ver=2.1.1' type='text/css' />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base2.css') }}">
  <title>{% block title %}Home{% endblock %}</title>
</head>
<header id="navbar" class="header" role="banner" style="  height: 100px; background-color: #010927; ">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel='stylesheet' id='cludo-styles-css'
    href='https://www.cludo.com/wp-content/themes/cludo/build/css/theme.min.css?ver=2.1.1' type='text/css'>
  <a class="navbar-brand" href="/">
    <div class="logo-image">
      <img src="../static/img/logo.png" class="img-fluid">
    </div>
  </a>
  <div class="header__container" style="background-color: #010927;  ">
    <nav id="site-navigation" class="header__nav" role="navigation" style="margin-top: -25px;">
      <div class="menu-primary-container">
        <ul id="menu-primary" class="nav nav__primary">
          {% if user.is_authenticated %}
          <!-- <li  class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7625"><a href="/sign-up">Register</a> -->
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7625"
            style="margin-top: -26px;">
            <i class="fa fa-caret-down"></i><a href="#" class="about">About</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7627"><a
                    href="/termsofservice">Terms of Service</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7628"><a
                    href="/privacy">Privacy</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7626"><a
                    href="/contactus">Contact</a></li>
              </ul>
            </div>
          </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6994">
            <a href="#">Discover</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6996"><a
                    href="/lawsandpolicies">Law and Policies</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6995"><a
                    href="/newsandinsights">News and insights</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6712"><a
                    href="/stockists">Stockists</a></li>
              </ul>
            </div>
          </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1520">
            <a href="#">Personal Investments</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <li class="menu-item menu-item-type-post_type menu-item-object-page current_page_parent menu-item-1531">
                  <a href="/portfolio">Portfolio</a>
                </li>
                <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                              href="/stocksearch">Stock Search</a></li> -->
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/quote">Quote</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/buy">Buy</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/sell">Sell</a></li>
                <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/deposit">Deposit</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/withdraw">Withdraw</a></li> -->
                <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                              href="/stockpage">Stock Page</a></li> -->
              </ul>
            </div>
          </li>
        </ul>
      </div>
      <a href="javascript:void(0);" class="header__search" data-toggle="search">
        <title>Search</title>
      </a>
      <div class="menu-utility-container">
        <ul id="menu-utility" class="nav nav__utility">
          <li id="menu-item-109"><a href="/logout"
              style="background-color: #4103d3; border-color:#4103d3; color: #FFFFFF;  margin-top: 13px; margin-left: 100px">Logout</a>
          </li>
        </ul>
      </div>
      <div class="menu-utility-container">
        <ul id="menu-utility" class="nav nav__utility">
          {% else %}
          <!-- <li  class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7625"><a href="/sign-up">Register</a> -->
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7625">
            <i class="fa fa-caret-down"></i><a href="#">About</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7627"><a
                    href="/termsofservice">Terms of Service</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7628"><a
                    href="/privacy">Privacy</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7626"><a
                    href="/contactus">Contact</a></li>
              </ul>
            </div>
          </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6994">
            <a href="#">Discover</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6996"><a
                    href="/lawsandpolicies">Law and Policies</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6995"><a
                    href="/newsandinsights">News and insights</a></li>
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6712"><a
                    href="/stockists">Stockists</a></li>
              </ul>
            </div>
          </li>
          <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1520">
            <a href="#">Personal Investments</a>
            <div class="dropdown dropdown__default">
              <ul role="menu" class="dropdown__menu">
                <!-- <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                              href="/stocksearch">Stock Search</a></li> -->
                <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6326"><a
                    href="/viewportfolio">View Portfolio</a></li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
      <div class="menu-utility-container">
        <ul id="menu-utility" class="nav nav__utility">
          <!-- <li  class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7625" ><a href="/sign-up">Register</a> -->
          <li id="menu-item-109" class="reg"><a href="/sign-up"
              style="background-color: #d96619; border-color:#d96619; color: #FFFFFF; ">Register</a></li>
          <li id="menu-item-109" class="log"><a href="/login"
              style="background-color: #19D97D; border-color:#19D97D; color: #FFFFFF; ">Login</a></li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </div>
</header>

<body>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category =='error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <!-- Site footer -->
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>About</h6>
          <p class="text-justify">BullyStockExchange.com <i>Investement is easy </i> and is an initiative to help the
            upcoming investors with their stocks. Bully Stock Exchange focuses on providing the most efficient stock
            search and portfolio management. We will help investors build up experience by offering a great range of
            services, daily newsletters and opportunities to increase their profits.
          </p>
        </div>
        <div class="col-xs-6 col-md-3">
          <h6>Categories</h6>
          <ul class="footer-links">
            <li><a href="#">About</a></li>
            <li><a href="#">Discover</a></li>
            <li><a href="#">Personal Investments</a></li>
          </ul>
        </div>
        <div class="col-xs-6 col-md-3">
          <h6>Quick Links</h6>
          <ul class="footer-links">
            <li><a href="/newsandinsights">News and insights</a></li>
            <li><a href="/contactus">Contact Us</a></li>
            <li><a href="/lawsandpolicies">Law and Policies</a></li>
            <li><a href="/privacy">Privacy Policy</a></li>
            <li><a href="/termsofservice">Terms of service</a></li>
          </ul>
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2022 All Rights Reserved by
            <a href="#">Bully</a>.
          </p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li><a class="facebook" href="#"><img src="/static/img/0bfd65cec6264f4eca5d4eb43d297f8c.png"><i
                  class="fa fa-facebook"></i></a></li>
            <li><a class="twitter" href="#"><i class="fa fa-twitter"><img
                    src="/static/img/0bfd65cec6264f4eca5d4eb43d297f8c copy.png"></i></a></li>
            <li><a class="dribbble" href="#"><i class="fa fa-dribbble"><img src="/static/img/2.png"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</body>

</html>

stock-exchange-private/website/templates/codeverification.html
{% extends "base.html" %}
{% block title %}Verification{% endblock %}
{% block content %}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/codeverification.css">
</head>
<div class="containerform">
    <div class="row">
        <div class="col-md-4 offset-md-4 form">
            <form method="POST">
                <img src="../static/img/Gmail-logo.jpg"
                    style="height:90px; width:100px; position:absolute; top:20px; left: 180px;">
                <br>
                <h2 class="text-center">You received the code in your gmail</h2>
                <br>
                <div class="form-group">
                    <input class="form-control" type="text" name="code" placeholder="Enter verification code" required>
                </div>
                <div class="form-group">
                    <button class="form-control button" type="submit" name="check" value="Submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<br><br><br>
<br><br><br>
<br><br><br>
{% endblock %}

stock-exchange-private/website/templates/newsandinsights.html
{% extends "base.html" %}
{% block title %}News and Insights{% endblock %}
{% block content %}

<head>
    <title>News and Insights</title>
    <link rel="stylesheet" href="../static/css/newsandinsights.css">

<body style="background-color:#F0F0F0;">
    <div class="Featured">
        <h2>News & Insights</h2>
        <h3>Featured Articles</h3>
        <br>
        <div class="line"></div>
        <div class="blog-card">
            <input type="radio" name="select" id="tap-1" checked>
            <input type="radio" name="select" id="tap-2">
            <input type="radio" name="select" id="tap-3">
            <input type="checkbox" id="imgTap">
            <div class="sliders">
                <label for="tap-1" class="tap tap-1"></label>
                <label for="tap-2" class="tap tap-2"></label>
                <label for="tap-3" class="tap tap-3"></label>
            </div>
            <div class="inner-part">
                <label for="imgTap" class="img">
                    <img class="img-1" src="../static/img/AAPL.jpeg">
                </label>
                <div class="content content-1">
                    <br>
                    <span>23rd April 2022</span>
                    <div class="title">
                        Apple Just Issued A Stunning $12 Billion Blow To Facebook
                    </div>
                    <div class="text">
                        Apple’s new privacy features continue to hit Facebook as iPhone users opt out from tracking on
                        their devices.
                    </div>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
            <div class="inner-part">
                <label for="imgTap" class="img">
                    <img class="img-2" src="../static/img/amazon.jpeg">
                </label>
                <div class="content content-2">
                    <br>
                    <span>21st January 2022</span>
                    <div class="title">
                        The Bag Is Heavy Going Into Q1 Earnings
                    </div>
                    <div class="text">
                        TextGiven the significant headwinds recently, the market will be watching Amazon's Q1
                        performance closely.
                    </div>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
            <div class="inner-part">
                <label for="imgTap" class="img">
                    <img class="img-3" src="../static/img/TSLA.jpeg">
                </label>
                <div class="content content-3">
                    <br>
                    <span>23rd March 2022</span>
                    <div class="title">
                        Elon Musk says he confronted Bill Gates about shorting Tesla
                    </div>
                    <div class="text">
                        In a tweet on Friday, the Tesla CEO admitted that he asked Gates if he was short-selling shares
                        of the electric carmaker.
                    </div>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="MainPg">
        <p><a href="{{ url_for('views.home') }}" style="color: #19D97D;">Home</a> > News & Insights</p>
        <br>
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="../static/img/get-paid-to-write-financial-articles.jpg" style="width:700px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <p style="margin-top: 20px;">24 April 2022</p>
                    <p>Personal Finance: How Do You Earn Long-Term Savings in 2022?</p>
                    <p>Savers are about to learn one painful and one surprising lesson about interest rates and banks.
                    </p>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
        </div>
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="../static/img/WordCloud.PNG" style="width:700px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <p style="margin-top: 20px;">22 March 2022</p>
                    <p>What’s next for the stock market as investors grapple with Fed near ‘peak hawkishness’ </p>
                    <p>Investors will watch for another gauge of U.S. inflation in the week ahead after the stock market
                        was rattled by the Federal Reserve ramping up its hawkish tone and suggesting large interest
                        rate hikes are coming to get an overheating economy under control.
                    </p>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
        </div>
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="../static/img/48440130557_578c09b89f_b.jpg" style="width:700px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <p style="margin-top: 20px;">13 April 2022</p>
                    <p>Sanctions on Russia: what are the ramifications of this new trade war?</p>
                    <p>Following the invasion of Ukraine, Western sanctions have targeted Russia’s trade, companies,
                        individuals and financial sector. The measures, which are far more wide-ranging than those
                        following the annexation of Crimea in 2014, raise big legal and economic issues for the world
                        trading system.
                    </p>
                    <button
                        onclick=" window.open('https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py','_blank')">Read
                        more
                    </button>
                </div>
            </div>
        </div>
        <div id="mySidenav" class="sidenav">
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="investing" style="background-color:#001a00; ">Investing</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="insights" style="background-color:#003300; ">Marketing Insights</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="stocks" style="background-color: #004d00;">Stocks</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="trading" style="background-color: #006600;">Trading</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="updates" style="background-color: #008000;">Bully Updates</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="profesional" style="background-color: #009900;">Profesional Traders</a>
            <a href="https://share.streamlit.io/qosz/streamlit-stock-exchange/main/dashboard.py" target="_blank"
                id="crypto" style="background-color: #00b300;">Crypto</a>
        </div>
    </div>
    <br><br><br><br>
</body>

</html>
{% endblock %}